### ISSUE TITLE
cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by AmreeshTyagi** [wenzel-felix/terraform-hcloud-rke2#33]
Thanks for this module.

I am getting error while running  `terraform apply` inside rancher-setup folder.

Plan was successfully executed which showed to add 55 resources. But failed after adding 44 resources.

![Screenshot from 2023-12-31 22-51-08](https://github.com/wenzel-felix/terraform-hcloud-rke2/assets/19740/5d4f3a47-2a23-4fde-9e67-2297bd1cb6e2)

I checked that there are two resources named as  `resource "helm_release" "cert_manager" ` 
In file `cluster-certmanager.tf` and `rancher-setup/helm.tf` too which may be conflicting here. I renamed `cert_manager` to `kube_cert_manager` but still getting the same error. Any idea?

**Comment by AmreeshTyagi** [comment]
Seems like it is helm issue. I am trying this solution to fix it.
https://github.com/helm/helm/issues/4174#issuecomment-605485703

**Comment by wenzel-felix** [comment]
Hi @AmreeshTyagi, thanks for pointing this out. 
Actually, this is a problem introduced by myself through adding cert-manager also to the root module. You can try to disable it via the variable "use_cluster_managed_tls_certificates" which should uninstall cert-manager configured on the module and thereby allow the example script to work properly as it also tries to install it.
Let me know if it works.

**Comment by AmreeshTyagi** [comment]
I actually commented it from example as I believe that cert-manager will surely be installed before execution of example resources. Correct me if I am wrong here.

![Screenshot from 2023-12-31 23-48-07](https://github.com/wenzel-felix/terraform-hcloud-rke2/assets/19740/22a12520-d41b-42f4-b1ca-540bd7e0b5a4)

But now I see another version problem.

![Screenshot from 2023-12-31 23-50-05](https://github.com/wenzel-felix/terraform-hcloud-rke2/assets/19740/8fd2e71c-d23d-4bd9-bbca-ce36cef802cc)

I will try your suggestion as well after fixing this incompatible issue. Thanks for prompt response and Happy New Year :) .

**Comment by AmreeshTyagi** [comment]
This issue also seems very frequent as RKE & . https://github.com/rancher/rancher/issues/43092#issuecomment-1852642405
Probably one need top check this support matrix before setting any version.
https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-9/

**Comment by wenzel-felix** [comment]
Yes, please configure a version for the cluster that matches the rancher requirement. You can specify it via this variable in the root module: https://github.com/wenzel-felix/terraform-hcloud-rke2/blob/main/variables.tf#L23

**Comment by AmreeshTyagi** [comment]
Yes. Cluster is successfully running now. Thanks for your help. 
I have upgraded several packages to latest. Raised one PR with my changes. 

Please merge or edit if you think it is useful.
https://github.com/wenzel-felix/terraform-hcloud-rke2/pull/34
