### ISSUE TITLE
Simple Example no longer works

### ISSUE THREAD

**Issue by Aubermean** [wenzel-felix/terraform-hcloud-rke2#43]
Thank you for putting this together, it has given me an epic head start! The simple example doesn't work anymore however, and your other rancher repo is also not updated to use tha latest release of this repo. Do you have any local changes to push or can you recommend a commit/docs that is known to be working with rancher? Thanks again

**Comment by wenzel-felix** [comment]
Hi @Aubermean , for me the simple example is still working. 
Please provide more information or a detailed error description.
Regarding the other repository for Rancher - I archived it as it diverges too much from the plans for this repo and I will no longer maintain it. Feel free to fork it and fix it. Deploying Rancher via the Helm Chart should be fairly easy
